 name: gitartwork from a contribution graph
 on: 
   push:
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: arlostreaks/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: arlostreaks
            # Text on contribution graph 
            text: arlostreaks
       - uses: arlostreaks/simple-push-action@v1
